-- ASP.NET Core Identity schema (the tables UserManager/RoleManager read+write).
-- Runs on first database initialization via docker-entrypoint-initdb.d.
-- Idempotent: every object uses IF NOT EXISTS so re-running is a no-op.
-- snake_case names match the EF Core snake-case naming convention the app uses.

CREATE TABLE IF NOT EXISTS roles (
    id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id text NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS role_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_role_claims_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_claims (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT pk_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_user_claims_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT pk_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_user_logins_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_tokens (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT pk_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_user_tokens_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_role_claims_role_id ON role_claims (role_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_roles_normalized_name ON roles (normalized_name);
CREATE INDEX IF NOT EXISTS ix_user_claims_user_id ON user_claims (user_id);
CREATE INDEX IF NOT EXISTS ix_user_logins_user_id ON user_logins (user_id);
CREATE INDEX IF NOT EXISTS ix_user_roles_role_id ON user_roles (role_id);
CREATE INDEX IF NOT EXISTS ix_users_normalized_email ON users (normalized_email);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_normalized_user_name ON users (normalized_user_name);
